USE [master]
GO
/****** Object:  Database [CarsInventory]    Script Date: 25-Oct-17 10:28:19 PM ******/
CREATE DATABASE [CarsInventory]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'CarsInventory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CarsInventory.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
-- LOG ON 
--( NAME = N'CarsInventory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CarsInventory_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
--GO
--IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
--begin
--EXEC [CarsInventory].[dbo].[sp_fulltext_database] @action = 'enable'
--end
GO
ALTER DATABASE [CarsInventory] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CarsInventory] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CarsInventory] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CarsInventory] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CarsInventory] SET ARITHABORT OFF 
GO
ALTER DATABASE [CarsInventory] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CarsInventory] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CarsInventory] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CarsInventory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CarsInventory] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CarsInventory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CarsInventory] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CarsInventory] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CarsInventory] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CarsInventory] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CarsInventory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CarsInventory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CarsInventory] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CarsInventory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CarsInventory] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CarsInventory] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CarsInventory] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CarsInventory] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CarsInventory] SET  MULTI_USER 
GO
ALTER DATABASE [CarsInventory] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CarsInventory] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CarsInventory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CarsInventory] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CarsInventory] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CarsInventory]
GO
/****** Object:  Table [dbo].[tblCars]    Script Date: 25-Oct-17 10:28:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblCars](
	[inCarId] [int] IDENTITY(1,1) NOT NULL,
	[stBrand] [nvarchar](100) NULL,
	[stModel] [nvarchar](100) NULL,
	[inYear] [int] NULL,
	[dcPrice] [decimal](12, 4) NULL,
	[flgIsNew] [bit] NULL,
 CONSTRAINT [PK_tblCars] PRIMARY KEY CLUSTERED 
(
	[inCarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [CarsInventory] SET  READ_WRITE 
GO
