//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCar
    {
        public int inCarId { get; set; }
        public string stBrand { get; set; }
        public string stModel { get; set; }
        public Nullable<int> inYear { get; set; }
        public Nullable<decimal> dcPrice { get; set; }
        public Nullable<bool> flgIsNew { get; set; }
    }
}
